Desarrollo/Libellus.Web/Areas/Administracion/Models/Maestros/MaestroViewModel.cs
namespace Libellus.Web.Areas.Administracion.Models.Maestros
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using Libellus.Entidades;
    using Libellus.Mensajes;
    using PagedList;

    /// <summary>
    /// Define la información a visualizar en la vista de un maestro.
    /// </summary>
    public class MaestroViewModel
    {
        /// <summary>
        /// Inicializa una nueva instancia de tipo MaestroViewModel.
        /// </summary>
        public MaestroViewModel()
        {
            this.TiposMaestro = new List<SelectListItem>();
        }

        /// <summary>
        /// Obtiene o establece el identificador interno del maestro.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno de la sede asociada.
        /// </summary>
        public int IdSede { get; set; }

        /// <summary>
        /// Obtiene o establece los tipos de maestro existentes.
        /// </summary>
        [Display(Name = "Maestro")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public short IdTipoMaestro { get; set; }

        /// <summary>
        /// Obtiene o establece los tipos de maestro existentes.
        /// </summary>
        public List<SelectListItem> TiposMaestro { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del tipo de maestro.
        /// </summary>
        [Display(Name = "Maestro")]
        public string NombreTipoMaestro { get; set; }

        /// <summary>
        /// Obtiene o establece la información del maestro seleccionado.
        /// </summary>
        public IPagedList<Maestro> Maestros { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del maestro.
        /// </summary>
        [Display(Name = "Nombre")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        [StringLength(100, ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1002")]
        public string Descripcion { get; set; }

        /// <summary>
        /// Obtiene o establece el estado del maestro.
        /// </summary>
        public bool Estado { get; set; }

        /// <summary>
        /// Obtiene o establece el token generado para determinar el estado de exportación a Excel.
        /// </summary>
        public string Token { get; set; }
    }
}

Desarrollo/Libellus.Web/Areas/Administracion/Controllers/MaestrosController.cs
namespace Libellus.Web.Areas.Administracion.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Mime;
    using System.Web.Mvc;
    using Libellus.Entidades;
    using Libellus.Entidades.Enumerados;
    using Libellus.Mensajes;
    using Libellus.Negocio.Administracion;
    using Libellus.Utilidades;
    using Libellus.Web.Areas.Administracion.Models.Maestros;
    using Libellus.Web.Controllers;
    using Libellus.Web.Helpers;
    using PagedList;

    /// <summary>
    /// Proporciona las acciones de interacción con la administración de los maestros.
    /// </summary>
    public class MaestrosController : AdministracionBaseController
    {
        #region Constructores

        /// <summary>
        /// Inicializa una instancia de tipo MaestrosController.
        /// </summary>
        public MaestrosController()
        {
            this.NegocioMaestros = new NegocioMaestros(this.UnidadDeTrabajoLibellus);
        }

        #endregion

        #region Acciones

        /// <summary>
        /// Renderiza la vista de consulta de administración de los maestros.
        /// </summary>
        /// <returns>Vista para consultar maestros administrables.</returns>
        [HttpGet]
        public ActionResult Consultar(int? pagina, short? idTipoMaestro, string nombreTipoMaestro)
        {
            MaestroViewModel maestroViewModel = new MaestroViewModel();

            try
            {
                if (idTipoMaestro.HasValue)
                {
                    maestroViewModel.IdTipoMaestro = idTipoMaestro.Value;
                    maestroViewModel.NombreTipoMaestro = nombreTipoMaestro;
                    //// TODO: JMG, Definir en dónde se almacenará el número de registros por página.
                    maestroViewModel.Maestros = this.NegocioMaestros.ConsultarMaestrosPorTipo((TiposMaestros)idTipoMaestro.Value, Utilidades.ContextoLibellus.ObtenerSedeActual).OrderByDescending(o => o.Estado).ThenBy(o => o.Descripcion).ToPagedList(pagina.Value, 10);
                }
                else
                {
                    maestroViewModel.Maestros = new List<Maestro>().ToPagedList(1, 10);
                }

                maestroViewModel.TiposMaestro = this.NegocioMaestros.ConsultarTipoMaestros().OrderBy(o => o.Descripcion).ToSelectListItem(o => o.Descripcion, o => o.Id);
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return View(maestroViewModel);
        }

        /// <summary>
        /// Renderiza la vista de creación para un maestro administrable.
        /// </summary>
        /// <param name="idTipoMaestro">Identificador interno del tipo de maestro seleccionado.</param>
        /// <param name="nombreMaestro">Valor del maestro a almacenar.</param>
        /// <returns>Vista para crear un maestro administrable.</returns>
        [HttpGet]
        public ActionResult Crear(short idTipoMaestro, string nombreMaestro)
        {
            MaestroViewModel maestroViewModel = new MaestroViewModel();
            maestroViewModel.NombreTipoMaestro = nombreMaestro;
            maestroViewModel.IdTipoMaestro = idTipoMaestro;

            ViewBag.NuevoRegistro = true;

            return View(maestroViewModel);
        }

        /// <summary>
        /// Almacena la información de un nuevo maestro administrable.
        /// </summary>
        /// <param name="maestro">Información del maestro a crear.</param>
        /// <param name="nombreMaestro">Nombre del tipo de maestro que se está tratando.</param>
        /// <returns>Vista para consultar maestros administrables.</returns>
        [HttpPost]
        public ActionResult Crear(Maestro maestro, string nombreMaestro)
        {
            try
            {
                Mensaje mensajeCreacion = this.NegocioMaestros.AlmacenarMaestro(maestro);

                if (mensajeCreacion == null)
                {
                    this.MostrarMensaje(new Mensaje(CodigoMensaje.Mensaje001));
                }
                else
                {
                    this.MostrarMensaje(mensajeCreacion);

                    MaestroViewModel maestroViewModel = new MaestroViewModel();
                    maestroViewModel.NombreTipoMaestro = nombreMaestro;
                    maestroViewModel.IdTipoMaestro = maestro.IdTipoMaestro;
                    ViewBag.NuevoRegistro = true;

                    return View(maestroViewModel);
                }
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return RedirectToAction("Consultar", new { pagina = 1, idTipoMaestro = maestro.IdTipoMaestro, nombreTipoMaestro = nombreMaestro });
        }

        /// <summary>
        /// Renderiza la vista de edición para un maestro administrable.
        /// </summary>
        /// <param name="idTipoMaestro">Identificador interno del tipo de maestro seleccionado.</param>
        /// <param name="idMaestro">Identificador interno del maestro a editar.</param>
        /// <param name="nombreMaestro">Nombre del tipo de maestro que se está tratando.</param>
        /// <returns>Vista para crear un maestro administrable.</returns>
        [HttpGet]
        public ActionResult Editar(short idTipoMaestro, int idMaestro, string nombreMaestro)
        {
            MaestroViewModel maestroViewModel = new MaestroViewModel();

            try
            {
                maestroViewModel.Id = idMaestro;
                maestroViewModel.NombreTipoMaestro = nombreMaestro;
                maestroViewModel.IdTipoMaestro = idTipoMaestro;

                Maestro maestro = this.NegocioMaestros.ConsultarMaestroPorId(idMaestro);
                maestroViewModel.IdSede = maestro.IdSede;
                maestroViewModel.Descripcion = maestro.Descripcion;
                maestroViewModel.Estado = maestro.Estado;
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            ViewBag.NuevoRegistro = false;

            return View(maestroViewModel);
        }

        /// <summary>
        /// Edita la información de un maestro administrable.
        /// </summary>
        /// <param name="maestro">Información del maestro a editar.</param>
        /// <param name="nombreMaestro">Nombre del tipo de maestro que se está tratando.</param>
        /// <returns>Vista para consultar maestros administrables.</returns>
        [HttpPost]
        public ActionResult Editar(Maestro maestro, string nombreMaestro)
        {
            try
            {
                Mensaje mensajeEdicion = this.NegocioMaestros.EditarMaestro(maestro);

                if (mensajeEdicion == null)
                {
                    this.MostrarMensaje(new Mensaje(CodigoMensaje.Mensaje002));
                }
                else
                {
                    this.MostrarMensaje(mensajeEdicion);

                    MaestroViewModel maestroViewModel = new MaestroViewModel();
                    maestroViewModel.NombreTipoMaestro = nombreMaestro;
                    maestroViewModel.IdTipoMaestro = maestro.IdTipoMaestro;
                    ViewBag.NuevoRegistro = false;

                    return View(maestroViewModel);
                }
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return RedirectToAction("Consultar", new { pagina = 1, idTipoMaestro = maestro.IdTipoMaestro, nombreTipoMaestro = nombreMaestro });
        }

        /// <summary>
        /// Exportar la información de un maestro a Excel.
        /// </summary>
        /// <param name="idTipoMaestro">Identificador interno del maestro a exportar su información a Excel.</param>
        /// <param name="nombreMaestro">Nombre del maestro a exportar.</param>
        /// <param name="token">Token generado para determinar el estado de exportación a Excel.</param>
        /// <returns>Array de bytes con la información exportada a Excel.</returns>
        [HttpGet]
        public ActionResult ExportarInformacionMaestro(int idTipoMaestro, string nombreMaestro, string token)
        {
            byte[] byteArray = null;
            string nombreArchivo = String.Format("Libellus_{0}.xlsx", nombreMaestro);
            this.Response.AppendCookie(new System.Web.HttpCookie("cookieExportarExcel", token));

            try
            {
                IEnumerable<object> listaMaestros = from p in this.NegocioMaestros.ConsultarMaestrosPorTipo((TiposMaestros)idTipoMaestro, Utilidades.ContextoLibellus.ObtenerSedeActual)
                                                    select new
                                                    {
                                                        Nombre = p.Descripcion,
                                                        Estado = UtilidadesApp.ObtenerNombreEstadoRegistro(p.Estado),
                                                        TipoMaestro = p.TipoMaestro.Descripcion
                                                    };


                byteArray = ExportarExcel.Exportar(listaMaestros.ToList(), nombreMaestro);
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return this.File(byteArray, MediaTypeNames.Application.Octet, nombreArchivo);
        }

        #endregion

        #region Métodos asíncronos

        /// <summary>
        /// Consulta la información de un maestos específico.
        /// </summary>
        /// <param name="pagina">Página a mostrar.</param>
        /// <param name="idTipoMaestro">Identificador interno del tipo de maestro a visualizar los datos.</param>
        /// <param name="nombreTipoMaestro">Nombre del tipo de maestro seleccionado.</param>

Desarrollo/Libellus.Web/Areas/Administracion/Views/Maestros/Consultar.cshtml
@model Libellus.Web.Areas.Administracion.Models.Maestros.MaestroViewModel

@{
    ViewBag.Title = "Administrar maestros";
}

<div id="mensaje"></div>

<div class="content-header">
    <h2 class="content-header-title">@ViewBag.Title</h2>
</div>

@using (Html.BeginForm("Crear", "Maestros", FormMethod.Get, new { area = "Administracion" }))
{
    <div class="form-group">
        @Html.LabelFor(model => model.IdTipoMaestro)
        @Html.DropDownListFor(model => model.IdTipoMaestro, Model.TiposMaestro, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdTipoMaestro, "", new { @class = "text-danger" })
        @Html.Hidden("nombreMaestro")
    </div>

    <div class="form-group" style="text-align: center !important;">
        <input type="submit" class="btn btn-primary" value="Crear maestro" />
    </div>

    <br />
    <br />
    @Html.Hidden("tokenExportarExcel")
    
    <div id="informacionMaestros">
        @if (Model.Maestros.Count() > 0)
        {
            Html.RenderPartial("_InformacionMaestros");
        }
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquerycookies")

    <script type="text/javascript">

        function EstablecerNombreMaestroSeleccionado() {
            /// <summary>Establece el nombre del maestro seleccionado en el hidden NombreMaestroSeleccionado.</summary>

            $('[name="nombreMaestro"]').val($('[name="IdTipoMaestro"] option:selected').text());
        }

        function ConsultarInformacionMaestro() {
            /// <summary>Consulta la información de un maestos específico.</summary>
            
            var token = new Date().getTime();
            $('[name="tokenExportarExcel"]').val(token);

            $.get('@Url.Action("ConsultarInformacionMaestros")?pagina=1&idTipoMaestro=' + $('[name="IdTipoMaestro"]').val() + "&nombreTipoMaestro=" + $('[name="nombreMaestro"]').val() + "&token=" + $('[name="tokenExportarExcel"]').val(), function (data) {
                $("#informacionMaestros").html(data);
            });
        }

        $(document).ready(function () {

            EstablecerNombreMaestroSeleccionado();

            $('[name="IdTipoMaestro"]').change(function () {

                if ($(this).val() == '') {
                    $("#informacionMaestros").html("");
                }
                else {
                    EstablecerNombreMaestroSeleccionado();
                    ConsultarInformacionMaestro();
                }

            });

        });

    </script>

}

Desarrollo/Libellus.Web/Areas/Administracion/Views/Maestros/Crear.cshtml
@model Libellus.Web.Areas.Administracion.Models.Maestros.MaestroViewModel

@{
    ViewBag.Title = "Crear maestro";
}

<div class="content-header">
    <h2 class="content-header-title">@ViewBag.Title</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    Html.RenderPartial("_Administrar");
    
    <br />

    <div class="form-group centered">
        @Html.BotonCancelar("Consultar", "Maestros", new { pagina = 1, idTipoMaestro = Model.IdTipoMaestro, nombreTipoMaestro = Model.NombreTipoMaestro }, new { tabindex = "4" })
        <input type="submit" value="Crear maestro" class="btn btn-primary" tabindex="3" />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Desarrollo/Libellus.Web/Areas/Administracion/Views/Maestros/Editar.cshtml
@model Libellus.Web.Areas.Administracion.Models.Maestros.MaestroViewModel

@{
    ViewBag.Title = "Editar maestro";
}

<div class="content-header">
    <h2 class="content-header-title">@ViewBag.Title</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    Html.RenderPartial("_Administrar");

    <br />

    <div class="form-group centered">
        @Html.BotonCancelar("Consultar", "Maestros", new { pagina = 1, idTipoMaestro = Model.IdTipoMaestro, nombreTipoMaestro = Model.NombreTipoMaestro }, new { tabindex = "4" })
        <input type="submit" value="Editar maestro" class="btn btn-primary" tabindex="3" />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Desarrollo/Libellus.Web/Areas/Administracion/Views/Maestros/_Administrar.cshtml
@model Libellus.Web.Areas.Administracion.Models.Maestros.MaestroViewModel

<div class="row">
    <div class="col-md-4 form-group">
        @Html.LabelFor(model => model.NombreTipoMaestro)
        @Html.TextBoxFor(model => model.NombreTipoMaestro, new { @class = "form-control", @readonly = "readonly" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.IdSede)
    </div>

    <div class="col-md-4 form-group">
        @Html.LabelFor(model => model.Descripcion)
        @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", maxlength = "100", tabindex = "1" })
        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
    </div>

    @if (!ViewBag.NuevoRegistro)
    {
        <div class="col-md-4 form-group">
            @Html.LabelFor(model => model.Estado)
            <div class="checkbox">
                @Html.CheckBoxFor(model => model.Estado, new { tabindex = "2" }) Activo
            </div>
        </div>
    }

</div>

Desarrollo/Libellus.Web/Areas/Administracion/Views/Maestros/_InformacionMaestros.cshtml
@model Libellus.Web.Areas.Administracion.Models.Maestros.MaestroViewModel

@if (Model.Maestros.Count == 0)
{
    @Html.Hidden("mensajeSinRegistros", @Libellus.Mensajes.Mensaje.Mensaje1005)
}
else
{
    <table class="@EstilosHelper.TablaLibellus">
        <tr>
            <th class="col-md-10">Nombre</th>
            <th class="col-md-1">Estado</th>
            <th class="col-md-1">Acciones</th>
        </tr>
        @foreach (var item in Model.Maestros)
        {
            <tr>
                <td>
                    @item.Descripcion
                </td>
                <td class="centered">
                    @Html.VisualizarEstado(item.Estado)
                </td>
                <td class="centered">
                    @Html.ActionLink("Editar", "Editar", "Maestros", new { idTipoMaestro = item.IdTipoMaestro, idMaestro = item.Id, nombreMaestro = Model.NombreTipoMaestro }, new { area = "Administracion" })
                </td>
            </tr>
        }

    </table>

    <div class="centered">
        @Html.PagedListPager(Model.Maestros, pagina => Url.Action("Consultar", new { pagina, idTipoMaestro = Model.IdTipoMaestro, nombreMaestro = Model.NombreTipoMaestro, token = Model.Token }))
    </div>

    <div class="form-group" style="text-align: center !important;">
        <a id="exportarExcel" href="@Url.Action("ExportarInformacionMaestro", new { idTipoMaestro = Model.IdTipoMaestro, nombreMaestro = Model.NombreTipoMaestro, token = Model.Token })" class="btn btn-success centered">Exportar a Excel</a>
    </div>
}

<script type="text/javascript">

    $(document).ready(function () {

        $("#exportarExcel").click(function () {

            $.cookie('cookieExportarExcel', @Model.Token);
            IniciarDescargaArchivo("exportarExcel");

        });

        if ($('[name="mensajeSinRegistros"]').val() == undefined){
            $('#mensaje').html('');
        }
        else {
            var mensajeHtml = "<div style=\"text-align: center !important\" class=\"alert alert-warning alert-dismissible\" role=\"alert\">";
            mensajeHtml += "         <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
            mensajeHtml += "             <span aria-hidden=\"true\">&times;</span>";
            mensajeHtml += "         </button>";
            mensajeHtml += $('[name="mensajeSinRegistros"]').val();
            mensajeHtml += "    </div>";

            $("#mensaje").html(mensajeHtml);

            setTimeout(function () {
                $('#mensaje').html('');
            }, 5000);
        }

    });

</script>