Desarrollo/Libellus.Web/Areas/Administracion/Models/Docente/DatosPersonalesViewModel.cs
namespace Libellus.Web.Areas.Administracion.Models.Docente
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using Exito.Sime.Web.Attributes;
    using Libellus.Mensajes;
    using Libellus.Web.Attributes;

    /// <summary>
    /// Define la información de los datos personales del docente.
    /// </summary>
    public class DatosPersonalesViewModel
    {
        /// <summary>
        /// Inicializa una nueva instancia de tipo DatosPersonalesViewModel.
        /// </summary>
        public DatosPersonalesViewModel()
        {
            this.TiposDocumento = new List<SelectListItem>();
            this.Sexos = new List<SelectListItem>();
            this.GrupoSanguineo = new List<SelectListItem>();
            this.EstadosCiviles = new List<SelectListItem>();
            this.Paises = new List<SelectListItem>();
            this.Departamentos = new List<SelectListItem>();
            this.Municipios = new List<SelectListItem>();
        }

        /// <summary>
        /// Obtiene o establece el identificador interno del tipo de documento de identidad.
        /// </summary>
        [Display(Name = "Tipo de documento de identidad")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public int IdTipoDocumento { get; set; }

        /// <summary>
        /// Obtiene o establece los tipos de documento existentes.
        /// </summary>
        public List<SelectListItem> TiposDocumento { get; set; }

        /// <summary>
        /// Obtiene o establece el documento de identidad del docente.
        /// </summary>
        [Display(Name = "Documento de identidad")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public string DocumentoIdentidad { get; set; }

        /// <summary>
        /// Obtiene o establece los nombres del docente.
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public string Nombres { get; set; }

        /// <summary>
        /// Obtiene o establece los apellidos del docente.
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public string Apellidos { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno del sexo del docente.
        /// </summary>
        [Display(Name = "Sexo")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public int IdSexo { get; set; }

        /// <summary>
        /// Obtiene o establece los sexos existentes.
        /// </summary>
        public List<SelectListItem> Sexos { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno del grupo sanguíneo del docente.
        /// </summary>
        [Display(Name = "Grupo sanguíneo")]
        public int? IdGrupoSanguineo { get; set; }

        /// <summary>
        /// Obtiene o establece los grupos sanguíneos existentes.
        /// </summary>
        public List<SelectListItem> GrupoSanguineo { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno del estado civil del docente.
        /// </summary>
        [Display(Name = "Estado civil")]
        public int? IdEstadoCivil { get; set; }

        /// <summary>
        /// Obtiene o establece los estados civiles existentes.
        /// </summary>
        public List<SelectListItem> EstadosCiviles { get; set; }

        /// <summary>
        /// Obtiene o establece el rol insitucional del docente.
        /// </summary>
        [Display(Name = "Rol institucional")]
        public string RolInstitucional { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno del rol insitucional del docente.
        /// </summary>
        public int IdRolInstitucional { get; set; }

        /// <summary>
        /// Obtiene o establece la fecha de nacimiento del docente.
        /// </summary>
        [Display(Name = "Fecha de nacimiento")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        [MayoriaEdadAttribute(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1014")]
        public string FechaNacimiento { get; set; }

        /// <summary>
        /// Obtiene o establece el correo electrónico personal del docente.
        /// </summary>
        [Display(Name = "Correo electrónico")]
        [EmailAttribute(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1012")]
        public string CorreoElectronico { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno del país de nacimiento del docente.
        /// </summary>
        [Display(Name = "País de nacimiento")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public short IdPaisNacimiento { get; set; }

        /// <summary>
        /// Obtiene o establece los países existentes.
        /// </summary>
        public List<SelectListItem> Paises { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno del departamento de nacimiento del docente.
        /// </summary>
        [Display(Name = "Departamento de nacimiento")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public short IdDepartamentoNacimiento { get; set; }

        /// <summary>
        /// Obtiene o establece los departamentos existentes.
        /// </summary>
        public List<SelectListItem> Departamentos { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador interno del municipio de nacimiento del docente.
        /// </summary>
        [Display(Name = "Municipio de nacimiento")]
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        public short IdMunicipioNacimiento { get; set; }

        /// <summary>
        /// Obtiene o establece los municipio existentes.
        /// </summary>
        public List<SelectListItem> Municipios { get; set; }

        /// <summary>
        /// Obtiene o establece el grado en el escalafón.
        /// </summary>
        [Display(Name = "Grado en el escalafón")]
        public int? IdEscalafon { get; set; }

        /// <summary>
        /// Obtiene o establece los posibles grados en el escalafón.
        /// </summary>
        public List<SelectListItem> Escalafones { get; set; }

        /// <summary>
        /// Obtiene o establece la descripción de la escalafón.
        /// </summary>
        public short Escalafon { get; set; }

        /// <summary>
        /// Obtiene o establece la fecha del último ascenso.
        /// </summary>
        [Display(Name = "Fecha último ascenso")]
        public string FechaUltimoAscenso { get; set; }

        /// <summary>
        /// Obtiene o establece la ruta de la foto del docente.
        /// </summary>
        [Display(Name = "Foto")]
        public string RutaFotoDocente { get; set; }

        /// <summary>
        /// Obtiene o establece la ruta de la firma del docente.
        /// </summary>
        [Display(Name = "Firma")]
        public string RutaFirmaDocente { get; set; }
    }
}

Desarrollo/Libellus.Web/Areas/GestionMatricula/Controllers/DatosGeneralesEstudianteController.cs
namespace Libellus.Web.Areas.GestionMatricula.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Mime;
    using System.Web;
    using System.Web.Mvc;
    using Libellus.Entidades;
    using Libellus.Entidades.Enumerados;
    using Libellus.Mensajes;
    using Libellus.Negocio.Administracion;
    using Libellus.Negocio.Matriculas;
    using Libellus.Negocio.Matriculas.Clases;
    using Libellus.Utilidades;
    using Libellus.Web.Areas.GestionMatricula.Models.DatosGeneralesEstudiante;
    using Libellus.Web.Helpers;
    using PagedList;

    /// <summary>
    /// Clase encargada de la interacción de los datos con la vista.
    /// </summary>
    public class DatosGeneralesEstudianteController : GestionMatriculaBaseController
    {
        /// <summary>
        /// Sede de la sesión.
        /// </summary>
        private int sedePrincipal = Utilidades.ContextoLibellus.ObtenerSedeActual;

        /// <summary>
        /// Inicializa una nueva instancia de la clase.
        /// </summary>
        public DatosGeneralesEstudianteController()
        {
            this.NegocioEstudiantes = new NegocioEstudiantes(this.UnidadDeTrabajoLibellus);
            this.NegocioMaestros = new NegocioMaestros(this.UnidadDeTrabajoLibellus);
            this.NegocioAntecedentesAcademicos = new NegocioAntecedentesAcademicos(this.UnidadDeTrabajoLibellus);
            this.NegocioMatriculas = new NegocioMatriculas(this.UnidadDeTrabajoLibellus);
        }

        /// <summary>
        /// Carga la vista principal de los datos del estudiante.
        /// </summary>
        /// <param name="id">Identificador del estudiante.</param>
        /// <returns>Retorna la vista principal.</returns>
        [HttpGet]
        public ActionResult Actualizar(int id, bool soloLectura)
        {
            EstudianteViewModel viewModel = null;

            try
            {
                EstudianteDatosPersonales estudiante = this.NegocioEstudiantes.ConsultarEstudiante(id);
                viewModel = this.EstablecerValoresModelo(estudiante);
                ViewBag.SoloLectura = soloLectura;
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
                return RedirectToAction("Bienvenida", "Home", new { area = "" });
            }

            return View(viewModel);
        }

        /// <summary>
        /// Actualiza la información del estudiante.
        /// </summary>
        /// <param name="estudiante">Datos del estudiante</param>
        /// <param name="postedFoto">Foto del estudiante.</param>
        /// <returns>Redirecciona a la acción Consultar.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(EstudianteDatosPersonales estudiante, HttpPostedFileBase postedFoto)
        {
            try
            {
                if (postedFoto != null)
                {
                    estudiante.Archivos = new EstudianteArchivo()
                    {
                        Foto = UtilidadesApp.ObtenerBytesArchivo(postedFoto.InputStream, postedFoto.ContentLength)
                    };
                }

                estudiante.ActualizarAntecedentes = true;
                this.NegocioEstudiantes.ActualizarEstudiante(estudiante);
                this.MostrarMensaje(new Mensaje(CodigoMensaje.Mensaje002));
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return RedirectToAction("Actualizar", new { id = estudiante.Id, soloLectura = false });
        }

        /// <summary>
        /// Retorna la vista consultar de los estudiantes.
        /// </summary>
        /// <returns>Retorna la vista.</returns>
        [HttpGet]
        public ActionResult Consultar(int? IdAnioLectivo, int? IdTipoIdentificacion, string Identificacion, int? IdEstado, int? IdGrado, string Grupo, int pagina = 1)
        {
            IEnumerable<EstudianteViewModel> estudiantes = new List<EstudianteViewModel>();

            try
            {
                if (Request.IsAjaxRequest())
                {
                    var query = this.NegocioEstudiantes.ConsultarEstudiantes(IdAnioLectivo, IdTipoIdentificacion, Identificacion, IdEstado, IdGrado, Grupo);
                    estudiantes = (from c in query
                                   select new EstudianteViewModel()
                                   {
                                       Id = c.Id,
                                       Nombre = c.Nombre,
                                       PrimerApellido = c.PrimerApellido,
                                       SegundoApellido = c.SegundoApellido,
                                       Usuario = new UsuarioViewModel() { Identificacion = c.Usuario.Identificacion },
                                       Estado = new Maestro()
                                       {
                                           Descripcion = c.Cupos
                                           .Where(e => !IdAnioLectivo.HasValue || e.IdAnioLectivo == IdAnioLectivo)
                                           .Select(e => e.Matriculas.FirstOrDefault().Estado.Descripcion).FirstOrDefault()
                                       }
                                   }).ToPagedList(pagina, 10);

                    return PartialView("_ResultadoConsulta", estudiantes);
                }
                else
                {
                    var tiposDocumento = this.NegocioMaestros.ConsultarMaestrosPorTipo(TiposMaestros.TiposIdentificaciones, sedePrincipal, true)
                        .OrderBy(e => e.Descripcion)
                        .ToSelectListItem(o => o.Descripcion, o => o.Id);

                    var estadosEstudiante = this.NegocioMaestros.ConsultarMaestrosPorTipo(TiposMaestros.EstadosMatricula, sedePrincipal, true)
                        .OrderBy(e => e.Descripcion)
                        .ToSelectListItem(o => o.Descripcion, o => o.Id);

                    var grados = this.NegocioMaestros.ConsultarMaestrosPorTipo(TiposMaestros.Grados, Utilidades.ContextoLibellus.ObtenerSedeActual, true)
                        .OrderBy(e => e.Descripcion)
                        .ToSelectListItem(o => o.Descripcion, o => o.Id);

                    ViewBag.TiposDocumento = tiposDocumento;
                    ViewBag.EstadosEstudiante = estadosEstudiante;
                    ViewBag.Grados = grados;
                }
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return View(estudiantes.ToPagedList(pagina, 10));
        }

        /// <summary>
        /// Realiza la consulta de un familiar de estudiante.
        /// </summary>
        /// <param name="identificacion">Identificacion del familiar.</param>
        /// <returns>Familiar serializado.</returns>
        public JsonResult ConsultarFamiliarEstudiante(string identificacion)
        {
            FamiliarViewModel familiar = new FamiliarViewModel();

            var query = this.NegocioEstudiantes.ConsultarFamiliarEstudiante(identificacion);

            if (query != null)
            {
                familiar = new FamiliarViewModel()
                {
                    Id = query.Id,
                    Barrio = query.Barrio,
                    Celular = query.Celular,
                    Correo = query.Correo,
                    Direccion = query.Direccion,
                    EsAcudiente = query.EsAcudiente ?? false,
                    Identificacion = query.Identificacion,
                    IdEstadoCivil = query.IdEstadoCivil ?? 0,
                    IdEstrato = query.IdEstrato ?? 0,
                    IdNivelEscolaridad = query.IdNivelEscolaridad,
                    IdParentesco = query.IdParentesco ?? 0,
                    IdTipoIdentificacion = query.IdTipoIdentificacion,
                    Nombres = query.Nombres,
                    Vive = query.Vive ?? false,
                    Telefono = query.Telefono
                };

                if (query.IdMunicipio.HasValue)
                {
                    familiar.IdMunicipio = query.IdMunicipio.Value;
                    familiar.IdDepartamento = query.Municipio.IdDepartamento;
                    familiar.IdPais = query.Municipio.Departamentos.IdPais;
                }
            }

            return Json(familiar);
        }

        /// <summary>
        /// Exportar la información de la funcionalidad.
        /// </summary>
        /// <param name="token">Token generado para determinar el estado de exportación a Excel.</param>
        /// <returns>Array de bytes con la información exportada a Excel.</returns>
        [HttpGet]
        public ActionResult ExportarInformacionExcel(string token)
        {
            byte[] byteArray = null;
            string nombreArchivo = "Libellus_datos_estudiante.xlsx";
            this.Response.AppendCookie(new System.Web.HttpCookie("cookieExportarExcel", token));

            try
            {
                IEnumerable<object> documentos = this.NegocioEstudiantes.ConsultarEstudiantes(null, null, null, null, null, null)
                    .Select(e => new
                    {
                        Documento_identidad = e.Usuario.Identificacion,
                        Estudiante = string.Format("{0} {1} {2}", e.Nombre, e.PrimerApellido, e.SegundoApellido),
                        Estado = e.Cupos.Select(f => f.Matriculas.FirstOrDefault().Estado.Descripcion).FirstOrDefault()
                    });

                byteArray = ExportarExcel.Exportar(documentos.ToList(), "DatosEstudiante");
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return this.File(byteArray, MediaTypeNames.Application.Octet, nombreArchivo);

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/DatosGeneralesEstudiante/Actualizar.cshtml
@model Libellus.Web.Areas.GestionMatricula.Models.DatosGeneralesEstudiante.EstudianteViewModel

@{
    ViewBag.Title = "Datos generales del estudiante";
    bool soloLectura = ViewBag.SoloLectura;
}

@Styles.Render("~/css/select2")
@Styles.Render("~/css/datetimepicker")
@Styles.Render("~/css/fileInput")

<div class="content-header">
    <h2 class="content-header-title">@ViewBag.Title</h2>
</div>

@using (Html.BeginForm("Actualizar", "DatosGeneralesEstudiante", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <ul id="tabs" class="nav nav-tabs">
        <li class=" active">
            <a href="#datosPersonales" data-toggle="tab">
                Datos personales
            </a>
        </li>
        <li>
            <a href="#datosResidenciales" data-toggle="tab">
                Datos residenciales
            </a>
        </li>
        <li>
            <a href="#datosFamiliares" data-toggle="tab">
                Datos familiares
            </a>
        </li>
        @if (!soloLectura)
        {
            <li>
                <a href="#datosEstado" data-toggle="tab">
                    Datos de estado y horario
                </a>
            </li>
        }
        <li>
            <a href="#datosAntecedentes" data-toggle="tab">
                Datos de antecedentes académicos
            </a>
        </li>
    </ul>

    <div id="contenidos" class="tab-content">
        <div class="tab-pane fade in active" id="datosPersonales">
            @Html.Partial("_DatosPersonales")
        </div>
        <div class="tab-pane fade" id="datosResidenciales">
            @Html.Partial("_DatosResidenciales")
        </div>
        <div class="tab-pane fade" id="datosFamiliares">
            @Html.Partial("_DatosFamiliares")
        </div>
        <div class="tab-pane fade" id="datosEstado">
            @Html.Partial("_DatosEstado")
        </div>
        <div class="tab-pane fade" id="datosAntecedentes">
            @Html.Partial("_DatosAntecedentes")
        </div>
    </div>

    <br />
    <div class="form-group centered">
        @if (ViewBag.SoloLectura)
        {
            @Html.ActionLink("Realizar otra consulta", "Consultar", null, new { @class = "btn btn-primary" })
        }
        else
        {
            @Html.BotonCancelar("Index", "DatosRestringidosEstudiante", null, new { tabindex = "8" })
            <input type="submit" value="Actualizar datos generales del estudiante" class="btn btn-primary" tabindex="7" />
        }
    </div>
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/js/datetimepicker")
    @Scripts.Render("~/js/cascadingDropDown")
    @Scripts.Render("~/js/fileInput")
    @Scripts.Render("~/js/unobstrusiveAjax")
    @Scripts.Render("~/js/underscore")

    <script type="text/javascript">

    $.validator.setDefaults({
        ignore: '.ignorar'
    });

    $("#imgFoto").on('fileclear', function (event) {
        $("#imgFoto").removeClass("ignorar");
    });

    if ($("#urlImagen").val() === "") {
        $("#imgFoto").fileinput({
            showUpload: false,
            showRemove: false,
            language: 'es',
            allowedFileExtensions: ["jpg", "png"]
        });
    }
    else {
        $("#imgFoto").addClass("ignorar");
        $("#imgFoto").fileinput({
            showUpload: false,
            showRemove: false,
            language: 'es',
            allowedFileExtensions: ["jpg", "png"],
            initialPreview: [
                "<img src='" + $("#urlImagen").val() + "' class='file-preview-image'>",
            ]
        });
    }

    var submitAntecedentes = function (value, index, ar) {
        var plantilla = _.template($("#plantillaDatosAntecedentes").html());
        $("#valoresAntecedentes").append(plantilla({
            id: value.Id,
            institucionEducativa: value.Institucion,
            idTipoInstitucion: value.IdTipoInstitucion,
            anio: value.Anio,
            idGrado: value.IdGrado,
            idMotivoRetiro: value.IdMotivoRetiro,
            observacion: value.Observacion,
            index: index
        }));
    };

    $(document).ready(function () {

        $("#cmbDepartamento").CascadingDropDown("#cmbPais", '@Url.Action("ConsultarDepartamentosResidenciales", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdDepartamento'
        });

        $("#cmbMunicipio").CascadingDropDown("#cmbDepartamento", '@Url.Action("ConsultarMunicipiosResidenciales", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdMunicipio'
        });

        $("#cmbDepartamentoNacimiento").CascadingDropDown("#cmbPaisNacimiento", '@Url.Action("ConsultarDepartamentosNacimiento", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdDepartamentoNacimiento'
        });

        $("#cmbMunicipioNacimiento").CascadingDropDown("#cmbDepartamentoNacimiento", '@Url.Action("ConsultarMunicipiosNacimiento", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdMunicipioNacimiento'
        });

        $("#cmbDepartamentoPadre").CascadingDropDown("#cmbPaisPadre", '@Url.Action("ConsultarDepartamentosPadre", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdDepartamentoPadre'
        });

        $("#cmbMunicipioPadre").CascadingDropDown("#cmbDepartamentoPadre", '@Url.Action("ConsultarMunicipiosPadre", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdMunicipioPadre'
        });

        $("#cmbDepartamentoMadre").CascadingDropDown("#cmbPaisMadre", '@Url.Action("ConsultarDepartamentosMadre", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdDepartamentoMadre'
        });

        $("#cmbMunicipioMadre").CascadingDropDown("#cmbDepartamentoMadre", '@Url.Action("ConsultarMunicipiosMadre", "Geografia", new { area = "" })', {
            idSelectedValue: '@Model.IdMunicipioMadre'
        });

        $('#dtpFechaNacimiento').datetimepicker({
            format: 'DD/MM/YYYY',
            locale: 'es'
        });

        $("form").submit(function () {
            listaAntecedentes.forEach(submitAntecedentes);
        });

    });
</script>

    <script type="text/html" id="plantillaDatosAntecedentes">
        <input type="hidden" name="AntecedentesAcademicos[<%= index %>].Id" value="<%= id %>" />
        <input type="hidden" name="AntecedentesAcademicos[<%= index %>].InstitucionEducativa" value="<%= institucionEducativa %>" />
        <input type="hidden" name="AntecedentesAcademicos[<%= index %>].IdTipoInstitucion" value="<%= idTipoInstitucion %>" />
        <input type="hidden" name="AntecedentesAcademicos[<%= index %>].Anio" value="<%= anio %>" />
        <input type="hidden" name="AntecedentesAcademicos[<%= index %>].IdGrado" value="<%= idGrado %>" />
        <input type="hidden" name="AntecedentesAcademicos[<%= index %>].IdMotivoRetiro" value="<%= idMotivoRetiro %>" />
        <input type="hidden" name="AntecedentesAcademicos[<%= index %>].Observacion" value="<%= observacion %>" />
    </script>
}

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/DatosGeneralesEstudiante/Consultar.cshtml
@model IPagedList<Libellus.Web.Areas.GestionMatricula.Models.DatosGeneralesEstudiante.EstudianteViewModel>

@{
    ViewBag.Title = "Consultar";
    object valorAnio = ViewBag.AnioLectivo;
}

<div class="content-header">
    <h2 class="content-header-title">Consultar estudiantes</h2>
</div>

@using (Html.BeginForm("Consultar", "DatosGeneralesEstudiante", FormMethod.Get, new { data_otf_ajax = "true", data_otf_target = "#resultado" }))
{
    <div class="row">
        <div class="form-group col-md-4">
            @Html.Partial("_AniosLectivos", valorAnio)
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.First().Usuario.IdTipoIdentificacion)
            @Html.DropDownList("IdTipoIdentificacion", ViewBag.TiposDocumento as IEnumerable<SelectListItem>, new { @class = "form-control", tabindex = "2" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.First().Usuario.Identificacion)
            @Html.TextBox("Identificacion", null, new { @class = "form-control", tabindex = "3", maxlength = "14" })
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.First().IdEstado)
            @Html.DropDownList("IdEstado", ViewBag.EstadosEstudiante as IEnumerable<SelectListItem>, new { @class = "form-control", tabindex = "4" })
        </div>

        <div class="form-group col-md-4">
            @Html.Label("Grado")
            @Html.DropDownList("IdGrado", ViewBag.Grados as IEnumerable<SelectListItem>, new { @class = "form-control", tabindex = "5" })
        </div>

        <div class="form-group col-md-4">
            @Html.Label("Grupo")
            <input type="number" min="0" max="999" name="Grupo" class="form-control" tabindex="6" maxlength="3" />
        </div>
    </div>

    <br />
    <div class="form-group centered">
        <input type="submit" value="Consultar" class="btn btn-primary" tabindex="7" />
    </div>
}

@Html.Partial("_ResultadoConsulta", Model)

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/DatosGeneralesEstudiante/_DatosEstado.cshtml
@model Libellus.Web.Areas.GestionMatricula.Models.DatosGeneralesEstudiante.EstudianteViewModel

@{
    bool soloLectura = true;
}

<div class="row">
    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.DatosEstado.FechaCreacion)
        @Html.TextBoxDisabledFor(model => model.DatosEstado.FechaCreacion, soloLectura, new { @class = "form-control", tabindex = "1" })
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.DatosEstado.FechaActualizacion)
        @Html.TextBoxDisabledFor(model => model.DatosEstado.FechaActualizacion, soloLectura, new { @class = "form-control", tabindex = "2" })
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.DatosEstado.EstadoEstudiante)
        @Html.TextBoxDisabledFor(model => model.DatosEstado.EstadoEstudiante, soloLectura, new { @class = "form-control", tabindex = "3" })
    </div>
</div>

<div class="row">
    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.DatosEstado.Horario)
        @Html.TextBoxDisabledFor(model => model.DatosEstado.Horario, soloLectura, new { @class = "form-control", tabindex = "4" })
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.DatosEstado.SalidaOcupacional)
        @Html.TextBoxDisabledFor(model => model.DatosEstado.SalidaOcupacional, soloLectura, new { @class = "form-control", tabindex = "5" })
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.DatosEstado.EstadoSalidaOcupacional)
        @Html.TextBoxDisabledFor(model => model.DatosEstado.EstadoSalidaOcupacional, soloLectura, new { @class = "form-control", tabindex = "6" })
    </div>
</div>