Desarrollo/Libellus.Web/Areas/GestionMatricula/Models/CancelacionMatricula/CancelacionMatriculaViewModel.cs
namespace Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula
{
    using Libellus.Mensajes;
    using PagedList;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    /// <summary>
    /// Clase para representar el view model de cancelación de matrícula.
    /// </summary>
    public class CancelacionMatriculaViewModel
    {
        /// <summary>
        /// Obtiene o establece el identificador de matricula.
        /// </summary>
        public int IdMatricula { get; set; }

        /// <summary>
        /// Obtiene o establece la observación.
        /// </summary>
        [MaxLength(1000)]
        [Display(Name = "Observaciones")]
        public string Observacion { get; set; }

        /// <summary>
        /// Obtiene o establece la salida ocupacional.
        /// </summary>
        [Display(Name = "Salida ocupacional")]
        public string SalidaOcupacional { get; set; }

        /// <summary>
        /// Obtiene  o establece el identificador del motivo.
        /// </summary>
        [Display(Name = "Motivo de retiro")]
        public int IdMotivo { get; set; }

        /// <summary>
        /// Obtiene  o establece el identificador del motivo.
        /// </summary>
        [Display(Name = "Motivo de retiro")]
        public int IdMotivoSalidaOcupacional { get; set; }

        /// <summary>
        /// Obtiene o establece listado de motivos.
        /// </summary>
        public IEnumerable<SelectListItem> MotivosRetiro { get; set; }
    }
}

Desarrollo/Libellus.Web/Areas/GestionMatricula/Models/CancelacionMatricula/ConsultaCancelacionMatriculaViewModel.cs
namespace Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula
{
    using PagedList;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    /// <summary>
    /// 
    /// </summary>
    public class ConsultaCancelacionMatriculaViewModel
    {
         /// <summary>
        /// Constructor de la clase.
        /// </summary>
        public ConsultaCancelacionMatriculaViewModel()
        {
            this.TiposDocumento = new List<SelectListItem>();
        }

        /// <summary>
        /// Obtiene o establece el identificador interno del tipo de documento de identidad.
        /// </summary>
        [Display(Name = "Tipo documento")]
        public int? IdTipoDocumento { get; set; }

        /// <summary>
        /// Obtiene o establece el documento de identidad del docente.
        /// </summary>
        [Display(Name = "Documento de identidad")]
        public string DocumentoIdentidad { get; set; }

        /// <summary>
        /// Año para la configuración.
        /// </summary>
        [Display(Name = "Año")]
        public int IdAnioLectivo { get; set; }

        /// <summary>
        /// Obtiene o establece los tipos de documento existentes.
        /// </summary>
        public List<SelectListItem> TiposDocumento { get; set; }

        /// <summary>
        /// Obtiene o establece los estados existentes.
        /// </summary>
        public List<SelectListItem> Estados { get; set; }

        /// <summary>
        /// Obtiene o establece las matriculas consultadas.
        /// </summary>
        public IPagedList<ResultadoConsultaCancelacionMatriculaViewModel> Matriculas { get; set; }
    }
}

Desarrollo/Libellus.Web/Areas/GestionMatricula/Models/CancelacionMatricula/ResultadoConsultaCancelacionMatriculaViewModel.cs
namespace Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    /// <summary>
    /// Clase para el resultado de la consulta de cancelación matricula.
    /// </summary>
    public class ResultadoConsultaCancelacionMatriculaViewModel
    {
        /// <summary>
        /// Obtiene o establece el identificador interno.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador del cupo.
        /// </summary>
        public int IdCupo { get; set; }

        /// <summary>
        /// Obtiene o establece el año.
        /// </summary>
        public int IdAnio { get; set; }

        /// <summary>
        /// Obtiene o establece el año.
        /// </summary>
        [Display(Name = "Año")]
        public short Anio { get; set; }

        /// <summary>
        /// obtien o estabblece si el año esta cerrado.
        /// </summary>
        public bool AnioCerrado { get; set; }

        /// <summary>
        /// Obtiene o establece el tipo de documento.
        /// </summary>
        public int IdTipoDocumento { get; set; }

        /// <summary>
        /// Obtiene o establece el tipo de documento.
        /// </summary>
        [Display(Name = "Tipo documento")]
        public string TipoDocumento { get; set; }

        // <summary>
        /// Obtiene o establece el documento de identidad.
        /// </summary>
        [Display(Name = "Documento identidad")]
        public string DocumentoIdentidad { get; set; }

        /// <summary>
        /// Obtiene o establece los nombres y apellidos.
        /// </summary>
        [Display(Name = "Estudiante")]
        public string Nombres { get; set; }

        /// <summary>
        /// Obtiene o establece el nivel educativo.
        /// </summary>
        [Display(Name = "Nivel educativo")]
        public string NivelEducativo { get; set; }

        /// <summary>
        /// Obtiene o establece grado al que aspira.
        /// </summary>
        [Display(Name = "Grado")]
        public string Grado { get; set; }

        /// <summary>
        /// Obtiene o establece la salida ocupacional.
        /// </summary>
        [Display(Name = "Salida ocupacional")]
        public string SalidaOcupacional { get; set; }

        /// <summary>
        /// Obtiene o establece el estado.
        /// </summary>
        [Display(Name = "Estado")]
        public string Estado { get; set; }

        /// <summary>
        /// Obtiene o establece el estado.
        /// </summary>
        public int Consecutivo { get; set; }

        /// <summary>
        /// Obtiene o establece el estado de la matricula.
        /// </summary>
        public int IdEstadoMatricula { get; set; }
    }
}

Desarrollo/Libellus.Web/Areas/GestionMatricula/Controllers/CancelacionMatriculaController.cs
namespace Libellus.Web.Areas.GestionMatricula.Controllers
{
    using Libellus.Entidades;
    using Libellus.Entidades.Enumerados;
    using Libellus.Negocio.Administracion;
    using Libellus.Negocio.Matriculas;
    using Libellus.Negocio.Matriculas.Clases;
    using Libellus.Utilidades;
    using Libellus.Web.Areas.GestionMatricula.Models.Matriculas;
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Mime;
    using System.Web.Mvc;
    using Libellus.Mensajes;
    using Libellus.Web.Helpers;
    using Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula;

    /// <summary>
    /// Gestiona las acciones de la cancelación de matricula.
    /// </summary>
    public class CancelacionMatriculaController : GestionMatriculaBaseController
    {
        #region Propiedades

        /// <summary>
        /// Identificador de la sede actual.
        /// </summary>
        private int SedeActual = Utilidades.ContextoLibellus.ObtenerSedeActual;

        #endregion

        #region Constructor

        /// <summary>
        /// Constructor de la clase.
        /// </summary>
        public CancelacionMatriculaController()
        {
            this.NegocioCupos = new NegocioCupos(this.UnidadDeTrabajoLibellus);
            this.NegocioMaestros = new NegocioMaestros(this.UnidadDeTrabajoLibellus);
            this.NegocioEstudiantes = new NegocioEstudiantes(this.UnidadDeTrabajoLibellus);
            this.NegocioDocumentacionSoporteRoles = new NegocioDocumentacionSoporteRoles(this.UnidadDeTrabajoLibellus);
            this.NegocioMatriculas = new NegocioMatriculas(this.UnidadDeTrabajoLibellus);
        }

        #endregion

        #region Acciones

        /// <summary>
        /// Realiza la cosulta de matriculas. 
        /// </summary>
        /// <param name="pagina">Paginación.</param>
        /// <param name="anio">Año seleccionado.</param>
        /// <param name="estado">Estado del cupo.</param>
        /// <param name="tipoDocumento">Tipo de documento.</param>
        /// <param name="documentoIdentidad">Documento de identidad.</param>
        /// <returns>Retorns el resultado de la consulta.</returns>
        [HttpGet]
        public ActionResult Consultar(int? pagina, int? IdAnioLectivo, int? IdTipoDocumento, string DocumentoIdentidad, bool consultar = false)
        {
            ConsultaCancelacionMatriculaViewModel consultarMatriculaViewModel = new ConsultaCancelacionMatriculaViewModel();
            consultarMatriculaViewModel.TiposDocumento = this.NegocioMaestros.ConsultarMaestrosPorTipo(TiposMaestros.TiposIdentificaciones, Utilidades.ContextoLibellus.ObtenerSedeActual).ToSelectListItem(o => o.Descripcion, o => o.Id, false);
            consultarMatriculaViewModel.Matriculas = new PagedList<ResultadoConsultaCancelacionMatriculaViewModel>(null, 1, 10);
            ViewBag.AnioLectivo = IdAnioLectivo;

            try
            {
                if (consultar)
                {
                    consultarMatriculaViewModel.Matriculas = (from m in this.NegocioMatriculas.Consultar(IdAnioLectivo, IdTipoDocumento, DocumentoIdentidad)
                                                              select new ResultadoConsultaCancelacionMatriculaViewModel
                                                              {
                                                                  Id = m.Id,
                                                                  IdAnio = m.Cupo.IdAnioLectivo,
                                                                  Anio = m.Cupo.AnioLectivo.Anio,
                                                                  AnioCerrado = m.Cupo.AnioLectivo.Cerrado,
                                                                  TipoDocumento = m.Cupo.Estudiante.Usuario.TipoIdentificacion.Descripcion,
                                                                  IdTipoDocumento = m.Cupo.Estudiante.Usuario.IdTipoIdentificacion,
                                                                  DocumentoIdentidad = m.Cupo.Estudiante.Usuario.Identificacion,
                                                                  Nombres = (m.Cupo.Estudiante.Nombre + " " + m.Cupo.Estudiante.PrimerApellido),
                                                                  NivelEducativo = m.Cupo.GradoPorNivel.Nivel.Descripcion,
                                                                  Grado = m.Cupo.GradoPorNivel.Grado.Descripcion,
                                                                  SalidaOcupacional = m.Cupo.SalidaOcupacional != null ? m.Cupo.SalidaOcupacional.Descripcion : string.Empty,
                                                                  Estado = m.Estado != null ? m.Estado.Descripcion : string.Empty,
                                                                  Consecutivo = m.Estado != null ? (int)m.Estado.Consecutivo : 0,
                                                                  IdEstadoMatricula = m.IdEstado,
                                                              }).OrderBy(m => m.Anio).ToPagedList(pagina ?? 1, 10);

                    ViewBag.Consultar = consultar;
                }
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return View(consultarMatriculaViewModel);
        }

        /// <summary>
        /// Exportar la información de la matricula a Excel.
        /// </summary>
        /// <param name="token">Token generado para determinar el estado de exportación a Excel.</param>
        /// <returns>Array de bytes con la información exportada a Excel.</returns>
        [HttpGet]
        public ActionResult ExportarInformacionExcel(string token)
        {
            byte[] byteArray = null;
            string nombreArchivo = "Libellus_Cancelacion_Matriculas.xlsx";
            this.Response.AppendCookie(new System.Web.HttpCookie("cookieExportarExcel", token));

            try
            {
                IEnumerable<object> aspectosEvaluativos = (from m in this.NegocioMatriculas.Consultar(null, null, null)
                                                           select new
                                                           {
                                                               Año = m.Cupo.AnioLectivo.Anio,
                                                               Tipo_Documento = m.Cupo.Estudiante.Usuario.TipoIdentificacion.Descripcion,
                                                               Documento_Identidad = m.Cupo.Estudiante.Usuario.Identificacion,
                                                               Estudiante = (m.Cupo.Estudiante.Nombre + " " + m.Cupo.Estudiante.PrimerApellido),
                                                               Nivel_Educativo = m.Cupo.GradoPorNivel.Nivel.Descripcion,
                                                               Grado = m.Cupo.GradoPorNivel.Grado.Descripcion,
                                                               Salida_Ocupacional = m.Cupo.SalidaOcupacional != null ? m.Cupo.SalidaOcupacional.Descripcion : string.Empty,
                                                               Estado = m.Estado != null ? m.Estado.Descripcion : string.Empty,
                                                           });

                byteArray = ExportarExcel.Exportar(aspectosEvaluativos.ToList(), "Cancelación matrículas");
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return this.File(byteArray, MediaTypeNames.Application.Octet, nombreArchivo);
        }

        /// <summary>
        /// Metodo get para la cancelación de la matricula.
        /// </summary>
        /// <param name="id">Identificador de la matricula.</param>
        /// <returns>Retorna el resultado de la acción.</returns>
        [HttpGet]
        public ActionResult CancelarMatricula(int id)
        {
            CancelacionMatriculaViewModel cancelacionMatriculaViewModel = new CancelacionMatriculaViewModel();
            Matricula matricula = this.NegocioMatriculas.ConsultarMatriculaPorId(id);
            cancelacionMatriculaViewModel.MotivosRetiro = this.NegocioMaestros.ConsultarMaestrosPorTipo(TiposMaestros.MotivosRetiroEstudiante, ContextoLibellus.ObtenerSedeActual).ToSelectListItem(o => o.Descripcion, o => o.Id, false);
            cancelacionMatriculaViewModel.SalidaOcupacional = matricula.Cupo.SalidaOcupacional == null ? string.Empty : matricula.Cupo.SalidaOcupacional.Descripcion;
            cancelacionMatriculaViewModel.IdMatricula = id;
            return View(cancelacionMatriculaViewModel);
        }

        /// <summary>
        /// Acción pots  para almacenar la cancelación de la matricula.
        /// </summary>
        /// <param name="id">Identificador de la matricula.</param>
        /// <returns>Retorna el resultado de la acción.</returns>
        [HttpPost]
        public ActionResult CancelarMatricula(CancelacionMatriculaViewModel cancelarMatriculaViewModel)
        {
            Matricula matricula = this.NegocioMatriculas.ConsultarMatriculaPorId(cancelarMatriculaViewModel.IdMatricula);
            matricula.CancelacionMatricula.Add(new CancelacionMatriculas
            {
                IdMatricula = cancelarMatriculaViewModel.IdMatricula,
                IdMotivoRetiro = string.IsNullOrEmpty(cancelarMatriculaViewModel.SalidaOcupacional) == true && cancelarMatriculaViewModel.IdMotivo > 0 ? cancelarMatriculaViewModel.IdMotivo : cancelarMatriculaViewModel.IdMotivoSalidaOcupacional,
                Observacion = cancelarMatriculaViewModel.Observacion
            });

            if (this.NegocioMatriculas.CancelarMatriculaSalidaOcupacional(matricula))
            {
                this.MostrarMensaje(new Mensaje(CodigoMensaje.Mensaje001));

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/CancelacionMatricula/CancelarMatricula.cshtml
@model Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula.CancelacionMatriculaViewModel

@{
    Html.EnableClientValidation(false);
    ViewBag.Title = "Cancelación de matrícula / Salida ocupacional";
}

<div class="content-header">
    <h2 class="content-header-title">@ViewBag.Title</h2>
</div>

@using (Html.BeginForm("CancelarMatricula", "CancelacionMatricula", FormMethod.Post, new { id = "formulario-cancelar-matricula" }))
{
    @Html.AntiForgeryToken()

    <ul id="tabs" class="nav nav-tabs">
        <li class=" active">
            <a href="#datosCancelacionMatricula" data-toggle="tab" id="tabCancelacionMatricula">
                Cancelación matrícula
            </a>
        </li>
        <li>
            <a href="#datosCancelacionSalidaOcupacional" data-toggle="tab" id="tabCancelacionSalidaOcupacional">
                Cancelación salida ocupacional
            </a>
        </li>
    </ul>

    <div id="contenidos" class="tab-content">
        <div class="tab-pane fade in active" id="datosCancelacionMatricula">
            @Html.Partial("_CancelarMatricula")
        </div>
        <div class="tab-pane fade" id="datosCancelacionSalidaOcupacional">
            @Html.Partial("_CancelarSalidaOcupacional")
        </div>
    </div>
    <br />
    <div class="form-group centered">
        @Html.HiddenFor(model => model.IdMatricula)
        @Html.BotonCancelar("Consultar", "CancelacionMatricula", null, new { tabindex = "4" })
        <input type="submit" id="Cancelar-matricula" class="btn btn-primary" value="Guardar" />
    </div>
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        function validarFormulario() {
            var validador = $('#formulario-cancelar-matricula').validate({
                rules: {
                    IdMotivo: {
                        required: true
                    },
                    IdMotivoSalidaOcupacional: {
                        required: true
                    }
                },
                messages: {
                    IdMotivo: '@Mensaje.Mensaje1001',
                    IdMotivoSalidaOcupacional: '@Mensaje.Mensaje1001'
                },
                errorClass: "input-validation-error field-validation-error",
                errorElement: "div"
            });
        }

        $(document).ready(function () {

            if ('@Model.SalidaOcupacional' == '') {
                $('#tabCancelacionSalidaOcupacional').hide()
            }

            $('#tabCancelacionSalidaOcupacional').click(function (e) {
                e.preventDefault()
                if ('@Model.SalidaOcupacional' !== '') {
                    $(this).tab('show')
                }
                else {
                    $('#tabCancelacionSalidaOcupacional').hide()
                }
            })

            validarFormulario();
        });

    </script>
}

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/CancelacionMatricula/Consultar.cshtml
@model Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula.ConsultaCancelacionMatriculaViewModel

@{
    ViewBag.Title = "Cancelación de matrícula / Salida ocupacional";
    Html.EnableClientValidation(false);
    object valorAnio = ViewBag.AnioLectivo;
}

<div class="content-header">
    <h2 class="content-header-title">@ViewBag.Title</h2>
</div>

<br />

@using (Html.BeginForm("Consultar", "CancelacionMatricula", FormMethod.Get, new { id = "formulario-consulta-cancelacionMatricula" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="form-group col-md-4">
            @Html.Partial("_AniosLectivos", valorAnio)
            @Html.ValidationMessageFor(model => model.IdAnioLectivo, "", new { @class = "text-danger" })
            @Html.Hidden("AnioSeleccionado")
        </div>
        <div class="col-md-4 form-group">
            @Html.LabelFor(model => model.IdTipoDocumento)
            @Html.DropDownListFor(model => model.IdTipoDocumento, Model.TiposDocumento, new { @class = "form-control", tabindex = "3" })
        </div>
        <div class="col-md-4 form-group">
            @Html.LabelFor(model => model.DocumentoIdentidad)
            @Html.TextBoxFor(model => model.DocumentoIdentidad, new { @class = "form-control", tabindex = "4", maxlength = "14" })
        </div>
    </div>
    <br />

    <div class="form-group" style="text-align: center !important;">
        <input type="submit" class="btn btn-primary centered" value="Consultar" tabindex="5" />
    </div>

    @Html.Hidden("consultar", true);

}

<br /><br />

@if (Model != null && Model.Matriculas.Count() > 0)
{
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="@EstilosHelper.TablaLibellus">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().Anio)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().TipoDocumento)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().DocumentoIdentidad)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().Nombres)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().NivelEducativo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().Grado)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().SalidaOcupacional)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Matriculas.First().Estado)
                        </th>
                        <th>Acción</th>
                    </tr>

                    @foreach (var item in Model.Matriculas)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Anio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoDocumento)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DocumentoIdentidad)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombres)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NivelEducativo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Grado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SalidaOcupacional)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Estado)
                            </td>
                            <td>
                                @if (item.Consecutivo == (int)ConsecutivoMaestros.EstadoMatriculaEstudianteMatriculado && item.AnioCerrado == false)
                                {
                                    @Html.ActionLink("Cancelar matrícula", "CancelarMatricula", new { id = item.Id })
                                }

                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

    <div class="centered paginacion">
        @Html.PagedListPager(Model.Matriculas, pagina => Url.Action("Consulta", new { pagina }))
    </div>

    <div class="form-group" style="text-align: center !important;">
        <button type="button" id="exportarExcel" class="btn btn-success centered" tabindex="8">Exportar a Excel</button>
    </div>

    @Html.Hidden("tokenExportarExcel")
}

@section Scripts {
    @Scripts.Render("~/bundles/general/js")
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $("#exportarExcel").bind("click", function () {

            $('[name="tokenExportarExcel"]').val(new Date().getTime());

            IniciarDescargaArchivo("exportarExcel");
            window.location.href = "@Url.Action("ExportarInformacionExcel")" + "?token=" + $('[name="tokenExportarExcel"]').val();
        });

        function MostrarMensajeSinInformacion() {

            if ($('table').length < 1 && '@ViewBag.Consultar') {
                var mensaje = @Html.Raw(Json.Encode(new Mensaje(CodigoMensaje.Mensaje1005)));
                VisualizarMensajeNegocio(mensaje.Tipo, mensaje.Texto, 7000);
            }
        }

        function validarFormulario() {
            var validador = $('#formulario-consulta-cancelacionMatricula').validate({
                rules: {
                    IdAnioLectivo: {
                        required: true
                    }
                },
                messages: {
                    IdAnioLectivo: '@Mensaje.Mensaje1001'
                },
                errorClass: "input-validation-error field-validation-error",
                errorElement: "div"
            });
        }

        $(document).ready(function () {
            MostrarMensajeSinInformacion();
            validarFormulario();
        });

    </script>
}

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/CancelacionMatricula/_CancelarMatricula.cshtml
@model Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula.CancelacionMatriculaViewModel

<div class="row">
    <div class="col-md-4 form-group">
        @Html.LabelFor(model => model.IdMotivo)
        @Html.DropDownListFor(model => model.IdMotivo, Model.MotivosRetiro, new { @class = "form-control", tabindex = "1" })
    </div>
    <div class="col-md-4 form-group">
        @Html.LabelFor(model => model.Observacion)
        @Html.TextAreaFor(model => model.Observacion, new { @class = "form-control", tabindex = "2" })
    </div>
</div>
<br />

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/CancelacionMatricula/_CancelarSalidaOcupacional.cshtml
@model Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula.CancelacionMatriculaViewModel

<div class="row">
    <div class="col-md-4 form-group">
        @Html.LabelFor(model => model.SalidaOcupacional)
        @Html.TextBoxFor(model => model.SalidaOcupacional, new { @class = "form-control", tabindex = "1", disabled = "disabled" })
    </div>
    <div class="col-md-4 form-group">
        @Html.LabelFor(model => model.IdMotivoSalidaOcupacional)
        @Html.DropDownListFor(model => model.IdMotivoSalidaOcupacional, Model.MotivosRetiro, new { @class = "form-control", tabindex = "2" })
    </div>
    <div class="col-md-4 form-group">
        @Html.LabelFor(model => model.Observacion)
        @Html.TextAreaFor(model => model.Observacion, new { @class = "form-control", tabindex = "3" })
    </div>
</div>
<br />

Desarrollo/Libellus.Web/Areas/GestionMatricula/Views/CancelacionMatricula/_ResultadoConsulta.cshtml
@model IPagedList<Libellus.Web.Areas.GestionMatricula.Models.CancelacionMatricula.ResultadoConsultaCancelacionMatriculaViewModel>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/general/js")

    <script type="text/javascript">

        function MostrarMensajeSinInformacion() {

            if ($('table').length < 1 && '@ViewBag.Consultar') {
                var mensaje = @Html.Raw(Json.Encode(new Mensaje(CodigoMensaje.Mensaje1005)));
                VisualizarMensajeNegocio(mensaje.Tipo, mensaje.Texto, 7000);
            }
        }

        $(document).ready(function () {
            MostrarMensajeSinInformacion();
        });

    </script>
}