Desarrollo/Libellus.Web/Areas/Administracion/Models/CuposPorNivel/CuposPorNivelConsultaViewModels.cs
namespace Libellus.Web.Areas.Administracion.Models.CuposPorNivel
{
    using Libellus.Entidades;
    using Libellus.Mensajes;
    using PagedList;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// View model Para la administración de la informacion de los cupos por nivel.
    /// </summary>
    public class CuposPorNivelConsultaViewModels
    {
        /// <summary>
        /// Contructor de la clase. 
        /// </summary>
        public CuposPorNivelConsultaViewModels()
        {
            AnioLectivo = new AnioLectivo();
            CuposPorNivel = new List<CuposPorNivelViewModels>();
        }

        /// <summary>
        /// Año del nivel educativo.
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(MensajesEstaticos), ErrorMessageResourceName = "Mensaje1001")]
        [Display(Name = "Año")]
        public int IdAnioLectivo { get; set; }

        /// <summary>
        /// Obtiene o establece la información de la configuración de cupos por nivel.
        /// </summary>
        public List<CuposPorNivelViewModels> CuposPorNivel { get; set; }

        /// <summary>
        /// Obtiene o establece el año lectivo asociado.
        /// </summary>
        public virtual AnioLectivo AnioLectivo { get; set; }

        /// <summary>
        /// Obtiene o establece el token generado para determinar el estado de exportación a Excel.
        /// </summary>
        public string Token { get; set; }
    }
}

Desarrollo/Libellus.Web/Areas/Administracion/Models/CuposPorNivel/CuposPorNivelViewModels.cs
namespace Libellus.Web.Areas.Administracion.Models.CuposPorNivel
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// View model Para la administración de la informacion de los cupos por nivel.
    /// </summary>
    public class CuposPorNivelViewModels
    {
        /// <summary>
        /// Identificador del registro.
        /// </summary>
        public int? Id { get; set; }

        /// <summary>
        /// Identificador del nivel.
        /// </summary>
        [Display(Name = "Identificador")]
        public int IdNivelEducativo { get; set; }

        /// <summary>
        /// Nivel asociado a la configuración.
        /// </summary>
        [Display(Name = "Nivel educativo")]
        public string NivelEducativo { get; set; }

        /// <summary>
        /// Numero de estudiantes por grupo.
        /// </summary>
        [Display(Name = "Estudiantes por grupo")]
        public int EstudiantesGrupo { get; set; }

        /// <summary>
        /// Numero de estudiantes esperados por nivel y grupo.
        /// </summary>
        [Display(Name = "Estudiantes esperados")]
        public int EstudiantesEsperados { get; set; }

        /// <summary>
        /// Calculo de cantidade de grupos.
        /// </summary>
        [Display(Name = "Cantidad de grupos")]
        public int CantidadGrupos { get; set; }

        /// <summary>
        /// Calculo de cantidad de docentes.
        /// </summary>
        [Display(Name = "cantidad de docentes")]
        public decimal CantidadDocentes { get; set; }

        /// <summary>
        /// Calculo de cantidad de docentes.
        /// </summary>
        [Display(Name = "Estudiantes matriculados")]
        public int? CantidadEstudiantesMatriculados { get; set; }

        /// <summary>
        /// Calculo del total de docentes.
        /// </summary>
        [Display(Name = "Total docentes")]
        public int? TotalDocentes { get; set; }

        /// <summary>
        /// Año del nivel educativo.
        /// </summary>
        [Display(Name = "Año")]
        public short IdAnio { get; set; }

        /// <summary>
        /// Consecutivo del nivel educativo.
        /// </summary>
        public int? Consecutivo { get; set; }
    }
}

Desarrollo/Libellus.Web/Areas/Administracion/Controllers/CuposPorNivelController.cs
namespace Libellus.Web.Areas.Administracion.Controllers
{
    using Libellus.Entidades;
    using Libellus.Entidades.Enumerados;
    using Libellus.Mensajes;
    using Libellus.Negocio.Administracion;
    using Libellus.Negocio.Administracion.Clases;
    using Libellus.Negocio.Matriculas.Clases;
    using Libellus.Utilidades;
    using Libellus.Web.Areas.Administracion.Models.CuposPorNivel;
    using Libellus.Web.Helpers;
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    /// <summary>
    /// Proporciona las acciones de interacción con la administración de los cupos por nivel.
    /// </summary>
    public class CuposPorNivelController : AdministracionBaseController
    {
        #region Constructores

        /// <summary>
        /// Inicializa una instancia de tipo CuposPorNivelController.
        /// </summary>
        public CuposPorNivelController()
        {
            this.NegocioCuposPorNivel = new NegocioCuposPorNivel(this.UnidadDeTrabajoLibellus);
            this.NegocioMaestros = new NegocioMaestros(this.UnidadDeTrabajoLibellus);
            this.NegocioAnioLectivo = new NegocioAnioLectivo(this.UnidadDeTrabajoLibellus);
            this.NegocioMatriculas = new NegocioMatriculas(this.UnidadDeTrabajoLibellus);
        }

        #endregion

        #region Acciones

        /// <summary>
        /// Metodo gest para la administración de cupos por nivel.
        /// </summary>
        /// <param name="pagina">Página para la aginación de la tabla.</param>
        /// <param name="IdAnioLectivo">Año seleccionado.</param>
        /// <returns>Retorna el resultado de la acción.</returns>
        [HttpGet]
        public ActionResult Administrar(int? pagina, int? IdAnioLectivo)
        {
            CuposPorNivelConsultaViewModels cuposPorNivelConsultaViewModels = new CuposPorNivelConsultaViewModels();

            try
            {
                List<AnioLectivo> anios = this.NegocioAnioLectivo.ConsultarAniosLectivos().ToList();
                AnioLectivo anoLectivo = anios.Where(x => x.Anio == DateTime.Now.Year).FirstOrDefault();
                cuposPorNivelConsultaViewModels.IdAnioLectivo = anoLectivo.Id;
                cuposPorNivelConsultaViewModels.AnioLectivo.Cerrado = anoLectivo.Cerrado;
                ViewBag.AnioLectivo = cuposPorNivelConsultaViewModels.IdAnioLectivo;

                if (IdAnioLectivo.HasValue)
                {
                    this.ObtenerInformacionCuposPorNivel(cuposPorNivelConsultaViewModels, IdAnioLectivo);
                }
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return View(cuposPorNivelConsultaViewModels);
        }

        /// <summary>
        /// Metodo post para almacenar la iformación.
        /// </summary>
        /// <param name="cuposPorNivel">Modelo para el almacenamiento.</param>
        /// <returns>Retorna el resultado de la acción</returns>
        [HttpPost]
        public JsonResult Administrar(List<CuposPorNivelViewModels> cuposPorNivel)
        {
            List<ProyeccionCuposPorNivel> ListaCuposPorNivel = new List<ProyeccionCuposPorNivel>();
            ProyeccionCuposPorNivel cupoPorNivel = new ProyeccionCuposPorNivel();
            try
            {
                foreach (var item in cuposPorNivel)
                {
                    cupoPorNivel = new ProyeccionCuposPorNivel()
                    {
                        Id = item.Id == null ? 0 : (int)item.Id,
                        IdNivel = item.IdNivelEducativo,
                        IdAnioLectivo = item.IdAnio,
                        EstudiantesEsperados = item.EstudiantesEsperados,
                        EstudiantesGrupo = item.EstudiantesGrupo,
                        CantidadGrupos = item.CantidadGrupos,
                        CantidadDocentes = item.CantidadDocentes
                    };

                    ListaCuposPorNivel.Add(cupoPorNivel);
                }

                if (NegocioCuposPorNivel.Administrar(ListaCuposPorNivel))
                {
                    this.MostrarMensaje(new Mensaje(CodigoMensaje.Mensaje001));
                }
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return Json(Url.Action("Administrar"));
        }

        /// <summary>
        /// Consulta la información de cupos por nivel.
        /// </summary>
        /// <param name="pagina">Pagina para realizar la páginación.</param>
        /// <param name="IdAnioLectivo">Año seleccionado.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ConsultarInformacionCuposPorNivel(int? anio)
        {
            CuposPorNivelConsultaViewModels cuposPorNivelConsultaViewModels = new CuposPorNivelConsultaViewModels();

            try
            {
                AnioLectivo anoLectivo = this.NegocioAnioLectivo.ConsultarAnioLectivo((int)anio);

                if (anoLectivo != null)
                {
                    cuposPorNivelConsultaViewModels.IdAnioLectivo = anoLectivo.Id;
                    cuposPorNivelConsultaViewModels.AnioLectivo.Cerrado = anoLectivo.Cerrado;
                    ViewBag.AnioLectivo = cuposPorNivelConsultaViewModels.IdAnioLectivo;
                }

                if (anio.HasValue)
                {
                    this.ObtenerInformacionCuposPorNivel(cuposPorNivelConsultaViewModels, anio);
                }
            }
            catch (Exception excepcion)
            {
                this.CapturarExcepcion(excepcion);
            }

            return PartialView("_InformacionCuposPorNivel", cuposPorNivelConsultaViewModels);
        }

        #endregion

        #region Métodos privados

        /// <summary>
        /// Obtiene la información de cupos por nivel.
        /// </summary>
        /// <param name="cuposPorNivelConsultaViewModels">Parametro para almacenar la información.</param>
        /// <param name="IdAnioLectivo">Año seleccionado.</param>
        private void ObtenerInformacionCuposPorNivel(CuposPorNivelConsultaViewModels cuposPorNivelConsultaViewModels, int? IdAnioLectivo)
        {
            cuposPorNivelConsultaViewModels.IdAnioLectivo = (int)IdAnioLectivo.Value;
            IEnumerable<ProyeccionCuposPorNivel> ListProyeccionCuposPorNivel = NegocioCuposPorNivel.ConsultarProyeccionCuposNivel((int)IdAnioLectivo.Value);
            IEnumerable<Maestro> ListaNiveles = NegocioMaestros.ConsultarMaestrosPorTipo(TiposMaestros.Nivel, Utilidades.ContextoLibellus.ObtenerSedeActual);

            cuposPorNivelConsultaViewModels.CuposPorNivel = ListaNiveles.GroupJoin(
                ListProyeccionCuposPorNivel,
                p => p.Id,
                c => c.IdNivel,
                (p, g) => g
                    .Select(c => new CuposPorNivelViewModels
                    {
                        Id = c.Id,
                        IdNivelEducativo = p.Id,
                        NivelEducativo = p.Descripcion,
                        Consecutivo = p.Consecutivo,
                        EstudiantesGrupo = c.EstudiantesGrupo,
                        EstudiantesEsperados = c.EstudiantesEsperados,
                        CantidadGrupos = c.CantidadGrupos,
                        CantidadDocentes = c.CantidadDocentes,
                        CantidadEstudiantesMatriculados = this.ConsultarCantidadEstudiantesMatriculadosPorNivel(p.Id, (int)IdAnioLectivo)
                    })
                    .DefaultIfEmpty(new CuposPorNivelViewModels
                    {
                        Id = null,
                        IdNivelEducativo = p.Id,
                        NivelEducativo = p.Descripcion,
                        Consecutivo = p.Consecutivo,
                        EstudiantesGrupo = 0,
                        EstudiantesEsperados = 0,
                        CantidadGrupos = 0,
                        CantidadDocentes = 0,
                        CantidadEstudiantesMatriculados = this.ConsultarCantidadEstudiantesMatriculadosPorNivel(p.Id, (int)IdAnioLectivo)
                    })
                ).SelectMany(g => g).ToList();
        }

        /// <summary>
        /// Consulta la cantidad de estudiantes matriculados por año y nivel.
        /// </summary>
        /// <param name="idNivel">Identficador del nivel.</param>
        /// <param name="idAnio">Identificador del año.</param>
        /// <returns>Retorna el resultadod de la consulta.</returns>
        private int ConsultarCantidadEstudiantesMatriculadosPorNivel(int idNivel, int idAnio)
        {
            return this.NegocioMatriculas.MatriculadosPorNivelAnioLectivo(idNivel, idAnio).Count();
        }

        #endregion
    }
}

Desarrollo/Libellus.Web/Areas/Administracion/Views/CuposPorNivel/Administrar.cshtml
@model Libellus.Web.Areas.Administracion.Models.CuposPorNivel.CuposPorNivelConsultaViewModels

@{
    ViewBag.Title = "Proyección y definición grupos y docentes por nivel";
    object valorAnio = ViewBag.AnioLectivo;
}

<div id="mensaje"></div>

<div class="content-header">
    <h2 class="content-header-title">@ViewBag.Title</h2>
</div>

@using (Html.BeginForm("Administrar", "CuposPorNivel", FormMethod.Post, new { area = "Administracion", id = "formulario-cupos-nivel" }))
{
    <div class="row">
        <div class="form-group col-md-4">
            @Html.Partial("_AniosLectivos", @valorAnio)
            @Html.ValidationMessageFor(model => model.IdAnioLectivo, "", new { @class = "text-danger" })
            @Html.Hidden("AnioSeleccionado")
        </div>
    </div>
    <br />
    <div id="informacionCuposPorNivel">
        @if (Model.CuposPorNivel != null && Model.CuposPorNivel.Count > 0)
        {
            Html.RenderPartial("_InformacionCuposPorNivel");
        }
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquerycookies")

    <script type="text/javascript">

        function ConsultarInformacionCuposPorNivel() {
            $.get('@Url.Action("ConsultarInformacionCuposPorNivel")?anio=' + $('[name="AnioSeleccionado"]').val(), function (data) {
                $("#informacionCuposPorNivel").html(data);
            });
        }

        $(document).ready(function () {

            if ('@Model.IdAnioLectivo' != '') {
                $('[name="AnioSeleccionado"]').val('@Model.IdAnioLectivo');
                ConsultarInformacionCuposPorNivel();
                if ('@Model.AnioLectivo.Cerrado' == 'True') {
                    $("#submitAdministrar").attr('disabled', 'disabled');
                }
                else {
                    $("#submitAdministrar").removeAttr('disabled');
                }
            }

            $("#IdAnioLectivo").change(function (e) {
               
                if ($("#IdAnioLectivo").val() == '') {
                    $("#informacionCuposPorNivel").html("");
                    $("#submitAdministrar").attr('disabled', 'disabled');
                }
                else {
                    $('[name="AnioSeleccionado"]').val($("#IdAnioLectivo").val());
                    ConsultarInformacionCuposPorNivel();
                    var cerrado = $("#IdAnioLectivo").trigger("EstadoAnio").data("resultado");

                    if (cerrado == 'true') {
                        $("#submitAdministrar").removeAttr('disabled');
                    }
                    else {
                        $("#submitAdministrar").attr('disabled', 'disabled');
                    }
                }
            });
        });

    </script>
}

Desarrollo/Libellus.Web/Areas/Administracion/Views/CuposPorNivel/_InformacionCuposPorNivel.cshtml
@model Libellus.Web.Areas.Administracion.Models.CuposPorNivel.CuposPorNivelConsultaViewModels

@if (Model.CuposPorNivel == null || Model.CuposPorNivel.Count == 0)
{
    @Html.Hidden("mensajeSinRegistros", @Libellus.Mensajes.Mensaje.Mensaje1005)
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="@EstilosHelper.TablaLibellus">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.CuposPorNivel.First().NivelEducativo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CuposPorNivel.First().EstudiantesGrupo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CuposPorNivel.First().EstudiantesEsperados)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CuposPorNivel.First().CantidadEstudiantesMatriculados)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CuposPorNivel.First().CantidadGrupos)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CuposPorNivel.First().CantidadDocentes)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CuposPorNivel.First().TotalDocentes)
                        </th>
                        <th>Acción</th>
                    </tr>
                    @foreach (var item in Model.CuposPorNivel)
                    {
                        <tr id="nivel@(item.Consecutivo)" name="filasCuposPorNivel" data-idcuposnivel="@item.Id" data-consecutivo="@item.Consecutivo" data-idnivel="@item.IdNivelEducativo">
                            <td>
                                @Html.DisplayFor(modelItem => item.NivelEducativo)
                            </td>
                            <td>
                                @Html.TextBoxFor(modelItem => item.EstudiantesGrupo, new { id = "estudiantesGrupo-" + item.IdNivelEducativo })
                            </td>
                            <td>
                                @Html.TextBoxFor(modelItem => item.EstudiantesEsperados, new { id = "estudiantesEsperados-" + item.IdNivelEducativo })
                            </td>
                            <td name="cantidadEstudiantesMatriculados">
                                @Html.DisplayFor(modelItem => item.CantidadEstudiantesMatriculados)
                            </td>
                            <td name="cantidadGrupos">
                                @Html.DisplayFor(modelItem => item.CantidadGrupos)
                            </td>
                            @if (item.Consecutivo != (int)ConsecutivoMaestros.NivelSecundaria && item.Consecutivo != (int)ConsecutivoMaestros.NivelMedia && item.Consecutivo != (int)ConsecutivoMaestros.NivelMediaTecnica)
                            {
                                <td name="cantidadDocentes">
                                    @Html.DisplayFor(modelItem => item.CantidadDocentes)
                                </td>
                            }
                            else
                            {
                                <td name="cantidadDocentes" class="cantidadDocentes">
                                    @Html.DisplayFor(modelItem => item.CantidadDocentes)
                                </td>
                            }
                            @if (item.Consecutivo != (int)ConsecutivoMaestros.NivelSecundaria && item.Consecutivo != (int)ConsecutivoMaestros.NivelMedia && item.Consecutivo != (int)ConsecutivoMaestros.NivelMediaTecnica)
                            {
                                <td name="totalDocentes">
                                    @Html.DisplayFor(modelItem => item.TotalDocentes)
                                </td>
                            }
                            else if (item.Consecutivo == (int)ConsecutivoMaestros.NivelSecundaria)
                            {
                                <td id="cellSecundaria" name="totalDocentes" rowspan="3">
                                    @Html.DisplayFor(modelItem => item.TotalDocentes)
                                </td>
                            }
                            <td>
                                <a href="#" onclick="Actualizar(nivel@(item.Consecutivo))">Actualizar</a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

    <div class="form-group centered">
        <input type="submit" id="submitAdministrar" value="Guardar cambios" class="btn btn-primary" tabindex="3" />
    </div>
}

<script type="text/javascript">

    function Actualizar(element) {
        ConfirmarAccion("Actualizar estudiantes esperados", "¿Está seguro de actualizar el registro?", function () {
            var fila = $(element);
            fila.find('[name="item.EstudiantesEsperados"]').val(fila.find('[name="cantidadEstudiantesMatriculados"]').text().trim());
            fila.find('[name="item.EstudiantesEsperados"]').keyup();
        });
    }

    function CalcularTotalDocentes(rowId, cantidadDocentes, secundaria) {
        var totalDocentes = 0;
        var cont = 0;
        if (secundaria) {
            $('.cantidadDocentes').each(function (index, val) {
                var valor = $(this).text().trim();
                if (valor != '' && !isNaN(valor)) {
                    totalDocentes += parseFloat(valor);
                    cont++;
                }
            });
            cont === 0 ? $('#cellSecundaria').html('') : $('#cellSecundaria').html(totalDocentes.toFixed(2));
        } else {
            $('#' + rowId + ' [name="totalDocentes"]').html(cantidadDocentes);
        }
    }

    function CalcularCantidadDocentes(rowId, cantidadGrupos) {
        var nivel = cantidadGrupos === '' ? -1 : $('#' + rowId).attr('data-consecutivo');
        var secundaria = cantidadGrupos === '' ? true : false;
        var cantidadDocentes;
        switch (nivel) {
            case '@((int)ConsecutivoMaestros.NivelPreescolar)':
                cantidadDocentes = cantidadGrupos;
                break;
            case '@((int)ConsecutivoMaestros.NivelPrimaria)':
                cantidadDocentes = cantidadGrupos;
                break;
            case '@((int)ConsecutivoMaestros.NivelSecundaria)':
                cantidadDocentes = (cantidadGrupos * 1.36).toFixed(2);
                secundaria = true;
                break;
            case '@((int)ConsecutivoMaestros.NivelMedia)':
                cantidadDocentes = (cantidadGrupos * 1.36).toFixed(2);
                secundaria = true;
                break;
            case '@((int)ConsecutivoMaestros.NivelMediaTecnica)':
                cantidadDocentes = (cantidadGrupos * 1.7).toFixed(2);
                secundaria = true;
                break;
            case '@((int)ConsecutivoMaestros.NivelClei)':
                cantidadDocentes = cantidadGrupos;
                break;
            default:
                cantidadDocentes = '';
        }
        $('#' + rowId + ' [name="cantidadDocentes"]').html(cantidadDocentes);
        CalcularTotalDocentes(rowId, cantidadDocentes, secundaria)
    }

    function CalcularCantidadGrupos(element) {
        var rowId = element.parent().parent().attr('id');
        var estudiantesGrupo = $('#' + rowId + ' [name="item.EstudiantesGrupo"]').val();
        var estudiantesEsperados = $('#' + rowId + ' [name="item.EstudiantesEsperados"]').val();
        if (estudiantesGrupo && estudiantesEsperados && estudiantesGrupo != '0') {
            var cantidadGrupos = Math.floor(estudiantesEsperados / estudiantesGrupo);
            $('#' + rowId + ' [name="cantidadGrupos"]').html(cantidadGrupos);
            CalcularCantidadDocentes(rowId, cantidadGrupos);
        } else {
            $('#' + rowId + ' [name="totalDocentes"]').html('');
            CalcularCantidadDocentes(rowId, '');
            $('#' + rowId + ' [name="cantidadGrupos"]').html('');
            $('#' + rowId + ' [name="cantidadDocentes"]').html('');
        }
    }

    function EstablecerOperacionesTabla() {
        var value = '';
        var regularExpression = /^\d+$/;
        $('[name="item.EstudiantesGrupo"], [name="item.EstudiantesEsperados"]').on('keydown', function (e) {
            var elemtValue = $(this).val();
            if (regularExpression.test(elemtValue))
                value = elemtValue;
        }).on('keyup', function (e) {
            var newElementValue = $(this).val();
            if (!newElementValue || regularExpression.test(newElementValue)) {
                var element = $(this);
                CalcularCantidadGrupos(element);
            } else if (!regularExpression.test(newElementValue)) {
                $(this).val(value);
                value = '';
            }
        });
        $('[name="item.EstudiantesGrupo"]').keyup();
    }

    function InhabilitarCampos() {
        if ('@Model.AnioLectivo.Cerrado' == 'True') {
            $('[name="item.EstudiantesGrupo"], [name="item.EstudiantesEsperados"]').attr('disabled', 'disabled');
        }
    }

    function HabilitarCampos() {

        if ('@Model.AnioLectivo.Cerrado' == 'False') {
            $('[name="item.EstudiantesGrupo"], [name="item.EstudiantesEsperados"]').removeAttr('disabled');
        }
    }

    function ValidarCuposPorNivel(idCupoNivel) {

        $('#submitAdministrar').on('click', function (event) {
            event.preventDefault();

            var validador = $('#formulario-cupos-nivel').validate({
                errorClass: "input-validation-error field-validation-error",
                errorElement: "div"
            });

            ReglasValidacion();

            var cont = 0;

            $('[name="item.EstudiantesGrupo"], [name="item.EstudiantesEsperados"]').each(function () {

                if (!validador.element(this)) cont++;
            });

            if (cont === 0) {
                GuardarCuposPornivel();
            }
        });
    }

    function ReglasValidacion() {
        $('[name="item.EstudiantesGrupo"]').each(function () {
            $(this).rules("add", {
                required: true,
                messages: {
                    required: "@Mensaje.Mensaje1001"
                }
            });
        });

        $('[name="item.EstudiantesEsperados"]').each(function () {
            $(this).rules("add", {
                required: true,
                messages: {
                    required: "@Mensaje.Mensaje1001"
                }
            });
        });
    }

    function GuardarCuposPornivel() {
        var cuposPorNivel = [];
        $('[name="filasCuposPorNivel"]').each(function (index, element) {
            var fila = $(this);
            cuposPorNivel.push({
                Id: fila.attr('data-idcuposnivel'),
                IdNivelEducativo: fila.attr('data-idnivel'),
                EstudiantesGrupo: fila.find('[name="item.EstudiantesGrupo"]').val(),
                EstudiantesEsperados: fila.find('[name="item.EstudiantesEsperados"]').val(),
                IdAnio: $('[name="AnioSeleccionado"]').val(),
                CantidadGrupos: Number(fila.find('[name="cantidadGrupos"]').text().replace(',', '.')),
                CantidadDocentes: Number(fila.find('[name="cantidadDocentes"]').text().replace(',', '.')),
            });
        });
        cuposPorNivel = JSON.stringify({ 'cuposPorNivel': cuposPorNivel });
        $.ajax({
            url: '@Url.Action("Administrar")',
            type: 'POST',
            data: cuposPorNivel,
            contentType: 'application/json',
            dataType: 'json',
            success: function (respuesta) {
                window.location.href = respuesta;
            },
            failure: function (respuesta) {
            }
        });
    }

    $(document).ready(function () {
        InhabilitarCampos();
        HabilitarCampos();
        EstablecerOperacionesTabla();
        ValidarCuposPorNivel();
    });

</script>